package:
  name: sed3
  version: "1.6.1"

source:
  git_rev: 1.6.1
  git_url: https://github.com/mjirik/sed3.git
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch: python
  ignore_run_exports:
    - python_abi
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sed3 = sed3:main
    #
    # Would create an entry point called sed3 that calls sed3.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - matplotlib
#    - pyyaml
    - scipy
    - numpy
#    - nose
#    - pyqt 4.11.*
    - pyqt 5.*

  run:
    - python
    - matplotlib
#    - pyyaml
    - scipy
#    - nose
    - numpy
    - pyqt 5.*

test:
  # Python imports
  imports:
    - sed3

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjirik/py3DSeedEditor
  license: MIT License
  summary: '3D viewer and editor of color seeds'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
